blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from .import views

app_name = 'blogs'
urlpatterns = [
	# Home page
	path('', views.index, name='index'),

	# Page that shows all posts
	path('blogposts/', views.blogposts, name='blogposts'),

	# Page that will add a new blog
	path('new_blog/', views.new_blog, name='new_blog'),

	# Page for editing blog posts.
	path('edit_blogpost/<int:blogpost_id>', views.edit_blogpost, name='edit_blogpost'),
]

users/urls.py
""" Defines the URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
	# Include default auth urls.
	path('', include('django.contrib.auth.urls')),

	# Registration page
	path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
	""" A blog the user has posted. """

	title = models.CharField(max_length=100)
	text = models.TextField(max_length=1000)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		"""Return a string representation of the model."""
		
		if len(self.text) >= 50:
			return f'{self.title} {self.text[:50]}...'

		else:
			return f'{self.title} {self.text}'

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from . models import BlogPost

class BlogForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'title': 'Title','text': 'Text',}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogForm

# Create your views here.

def index(request):
	""" The home page for blogs. """
	return render(request, 'blogs/index.html')


def check_blog_owner(blogpost, request):
	""" check if the blogpost belongs to the owner """
	if blogpost.owner != request.user:
		raise Http404

def blogposts(request):
	""" Show all posts. """
	blogpost = BlogPost.objects.order_by('-date_added')
	context = {'blogpost': blogpost}
	return render(request, 'blogs/blogposts.html', context)

@login_required
def new_blog(request):
	""" Add a new blog """
	if request.method != 'POST':
		# No data submitted, create a blank form
		form = BlogForm()
	else:
		# POST data submitted; process data.
		form = BlogForm(data=request.POST)
		if form.is_valid():
			new_post = form.save(commit=False)
			new_post.owner = request.user
			new_post.save()
			form.save()
			return redirect('blogs:blogposts')

	# Display blank or invalid form.
	context = {'form': form}
	return render(request, 'blogs/new_blog.html', context)

@login_required
def edit_blogpost(request, blogpost_id):
	"""Edit an existing blogpost"""
	blogpost = BlogPost.objects.get(id=blogpost_id) # blog id number
	blog = blogpost # blog data which includes the title. text etc.

	check_blog_owner(blogpost, request)

	if request.method != 'POST':
		# Intial request; pre-fill form with current blog post.
		form = BlogForm(instance=blogpost)
	else:
		# POST data submitted, process data.
		form = BlogForm(instance=blogpost, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blogs:blogposts')

	context = {'blogpost': blogpost, 'blog': blog, 'form': form}
	return render(request, 'blogs/edit_blogpost.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
	""" Register a new user """
	if request.method != 'POST':
		# Display a blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form.
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('blogs:index')

	# Display a blank or invalid form
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Chen Blogs! </title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>

	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border sticky-top">
		<a class="navbar-brand" href="{% url 'blogs:index' %}">Blog Site</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">	
				<li class="nav-item">
					<a class="nav-link" href="{% url 'blogs:blogposts' %}">blogposts</a>
				</li>
			</ul>
			<ul class="navbar-nav m1-auto">
				{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text">Hello, {{ user.username }}!</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'blogs:new_blog' %}">Add new Blog</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a>
				</li>
				{% endif %}
			</ul>
		</div>

	</nav>

	<main>
		<div>
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>
</body>
</html>

blogs/templates/blogs/blogposts.html
{% extends "blogs/base.html" %}

{% block page_header %}
<h1>{{ blogpost.title }}</h1>
{% endblock page_header %}

{% block content %}
<div class="container">
	
	{% if user.is_authenticated %}
		<p>
			<a href="{% url 'blogs:new_blog' %}">Add a new post</a>
		</p>
	{% else %}
		<p>
			<a href="{% url 'users:login' %}">Login to add new post</a>
		</p>
	{% endif %}

		{% for blog in blogpost %}
		<h4>{{ blog.title }}</h4>
			<div class="card mb-3">
				<h4 class="card-header">
					{{ blog.date_added|date:'d / M / Y - H:i' }}

					<small>
						<a href="{% url 'blogs:edit_blogpost' blog.id %}">Edit Post</a>
					</small>
				</h4>
				<div class="card-body">
					{{ blog.text|linebreaks }}
				</div>
				<p class="card-header">
					Created by: {{ blog.owner }}
				</p>
			</div>
			{% empty %}
				<li><h3>No Blog posts have been added yet.</h3></li>
			{% endfor %}
</div>
{% endblock content %}

blogs/templates/blogs/edit_blogpost.html
{% extends "blogs/base.html" %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
	<h3>
		<a href="{% url 'blogs:blogposts' %}">Go back</a>
	</h3>
	<h2>Edit Blog</h2>
	<form action="{% url 'blogs:edit_blogpost' blog.id %}" method="post">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
		<button name="submit" class="btn btn-primary">Submit</button>
		{% endbuttons %}
		<input type="hidden" name="next" value="{% url 'blogs:index' %}" />
	</form>
</div>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}


{% block page_header %}

<div class="jumbotron">
    <h1 class="display-4">Add your posts</h1>
    <p class="lead">On this website you will be able to add your blog posts</p>
    <hr class="my-4">
    <p>Welcome and i hope you enjoy your visit here. </p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}" role="button">Register here</a>
    </p>
</div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
<div>
	<h2 class="container">Add new post here: </h2>
</div>
{% endblock page_header %}

{% block content %}
<div class="container">
	<form action="{% url 'blogs:new_blog' %}" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<button name="submit" class="btn btn-primary">Post Blog</button>
		{% endbuttons %}
		
	</form>
</div>
{% endblock content %}